name: 同步上游仓库

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/原作者/原仓库名.git
          
      - name: 获取上游更改
        run: |
          git fetch upstream
          
      - name: 同步分支
        run: |
          git checkout main  # 或者你的主分支名称
          git merge upstream/main
          
      - name: 推送更改
        run: |
          git push origin main
